### ISSUE TITLE
Challenge Submission - Sorting 101

### ISSUE THREAD

**Issue by xvillaneau** [pyatl/jam-sessions#29]
# Synopsis

Sorting is arguably among the fundamental problems in Computer Science. Thankfully we rarely need to think about it too much. Like most other high-level programming languages, Python includes built-in sorting routines that use fast and efficient (and complex) algorithms. Sorted collections are always just one `sorted()` call away!

While not essential to all programming tasks, understanding how sorting works is quite useful. While the concept of sorting is very simple, the techniques used to achieve it can be very complex. Sorting problems are also a very common type of interview questions, so it pays to be prepared.

The core of the exercise is to sort a list of signed integers without using the built-in sorting calls. The challengers are free to use any sorting algorithm they want. For those who have never implemented sorting before, the insertion sort will be explained in the instructions. More advanced coders are invited to implement a more complicated algorithm of their choosing.

**Comment by fimion** [comment]
i love it!
